package specman.model.v002.io;

import specman.Aenderungsart;
import specman.SpecmanVersion;
import specman.model.v002.AbstractEditAreaModel_V002;
import specman.model.v002.AbstractStepModel_V002;
import specman.model.v002.BranchSequenceModel_V002;
import specman.model.v002.BreakStepModel_V002;
import specman.model.v002.CaseStepModel_V002;
import specman.model.v002.CatchAreaModel_V002;
import specman.model.v002.CatchSequenceModel_V002;
import specman.model.v002.ChangeInfoModel_V002;
import specman.model.v002.CoCatchModel_V002;
import specman.model.v002.DiagramModel_V002;
import specman.model.v002.DoWhileStepModel_V002;
import specman.model.v002.PdfExportOptionsModel_V002;
import specman.model.v002.EditorContentModel_V002;
import specman.model.v002.IfElseStepModel_V002;
import specman.model.v002.IfStepModel_V002;
import specman.model.v002.ImageEditAreaModel_V002;
import specman.model.v002.ListItemEditAreaModel_V002;
import specman.model.v002.Markup_V002;
import specman.model.v002.StepSequenceModel_V002;
import specman.model.v002.SubsequenceStepModel_V002;
import specman.model.v002.TableEditAreaModel_V002;
import specman.model.v002.TextEditAreaModel_V002;
import specman.model.v002.WhileStepModel_V002;

import java.util.Arrays;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import static specman.model.v002.io.ModelKeyword_V002.*;

/** Serializes a {@link DiagramModel_V002} to the SpecmanModel_V002 text format (.nsd). */
public class ModelSerializer_V002 {

    public static final String COMMENT_INTRO = "//";

    private static final Pattern BODY_PATTERN = Pattern.compile("<body>([\\s\\S]*?)</body>");

    private final StringBuilder sb = new StringBuilder();
    private int indentionLevel = 0;

    private String indent() {
        return "    ".repeat(indentionLevel);
    }

    /** Serializes a DiagramModel_V002 to SpecmanModel_V002 text format. */
    public String serialize(DiagramModel_V002 model) {
        Map<String, String> idToStepNumber = buildIdToStepNumber(model);
        sb.setLength(0);
        indentionLevel = 0;

        // First line: JSON envelope — read by Jackson, skipped by ANTLR
        sb.append(COMMENT_INTRO + " {\"specmanVersion\":\"").append(SpecmanVersion.getVersion())
          .append("\",\"modelType\":\"").append(DiagramModel_V002.class.getName()).append("\"}\n");
        sb.append(COMMENT_INTRO + " Specman: ").append(model.name != null ? model.name : "").append("\n");
        sb.append(COMMENT_INTRO + " Format defined by grammar: SpecmanModel_V002.g4\n");
        sb.append(COMMENT_INTRO + " Step numbers (first parameter of each step): unique diagram-wide; referenced by catch blocks and step links in text; sanitizer renumbers consistently\n");
        sb.append(COMMENT_INTRO + " plain=`...` fields: plain-text rendition, regenerated by Specman on every sanitize run\n");
        sb.append(COMMENT_INTRO + " markups=[...] fields: change-tracking annotations, maintained by Specman\n");
        sb.append(COMMENT_INTRO + " image(...) { [base64:...] } blocks: embedded binary image data (base64-encoded)\n");

        appendSettings(model);

        if (hasContent(model.intro)) {
            sb.append("\n");
            blockOpen(INTRO, editContainerHead(model.intro));
            appendEditContainerTail(model.intro, 1);
            blockClose();
        }

        sb.append("\n");
        blockOpen(MAIN_SEQUENCE);
        appendSteps(model.mainSequence, idToStepNumber);
        appendCatchArea(model.mainSequence != null ? model.mainSequence.catchArea : null, idToStepNumber);
        blockClose();

        if (hasContent(model.outro)) {
            sb.append("\n");
            blockOpen(OUTRO, editContainerHead(model.outro));
            appendEditContainerTail(model.outro, 1);
            blockClose();
        }

        return sb.toString();
    }

    private boolean hasContent(EditorContentModel_V002 container) {
        return container != null && container.areas != null && !container.areas.isEmpty();
    }

    private void appendSettings(DiagramModel_V002 model) {
        sb.append("\n");
        blockOpen(SETTINGS);
        sb.append(indent()).append(WIDTH).append("=").append(model.width).append("\n");
        sb.append(indent()).append(ZOOM).append("=").append(model.zoomFactor).append("\n");
        sb.append(indent()).append(CHANGE_MODE).append("=").append(model.changeModeEnabled).append("\n");
        sb.append(indent()).append(CHANGESET_NAME).append("=").append(model.changeSetName != null ? model.changeSetName : "yellow").append("\n");
        if (model.pdfExportOptions != null) {
            PdfExportOptionsModel_V002 pdf = model.pdfExportOptions;
            blockOpen(PDF_OPTIONS);
            if (pdf.filename != null) {
                sb.append(indent()).append(FILENAME).append("=`").append(pdf.filename).append("`\n");
            }
            if (pdf.modelFilename != null) {
                sb.append(indent()).append(MODEL_FILENAME).append("=`").append(pdf.modelFilename).append("`\n");
            }
            if (pdf.pageSize != null) {
                sb.append(indent()).append(PAGE_SIZE).append("=").append(pdf.pageSize).append("\n");
            }
            sb.append(indent()).append(PORTRAIT).append("=").append(pdf.portrait).append("\n");
            sb.append(indent()).append(PAGING).append("=").append(pdf.paging).append("\n");
            blockClose();
        }
        blockClose();
    }

    // ---- id → stepNumber map ----

    private Map<String, String> buildIdToStepNumber(DiagramModel_V002 model) {
        Map<String, String> map = new LinkedHashMap<>();
        for (AbstractStepModel_V002 step : model.queryAllSteps()) {
            if (step.id != null && step.stepNumber != null) {
                map.put(step.id, step.stepNumber);
            }
        }
        return map;
    }

    // ---- HTML body extraction ----

    private String extractBodyHtml(String text) {
        if (text == null) {
            return "";
        }
        Matcher m = BODY_PATTERN.matcher(text);
        if (m.find()) {
            return m.group(1).trim();
        }
        return text.trim();
    }

    private String escapeBackticks(String text) {
        if (text == null) {
            return "";
        }
        return text.replace("`", "'");
    }

    // ---- htmlContent: `html`, plain=`...`, markups=[...] ----

    private String htmlContent(TextEditAreaModel_V002 area) {
        StringBuilder hb = new StringBuilder();
        hb.append("`").append(escapeBackticks(extractBodyHtml(area.text))).append("`");

        if (area.plainText != null && !area.plainText.isEmpty()) {
            String plain = escapeBackticks(area.plainText.replaceAll("^\\n", ""));
            hb.append(", ").append(PLAIN).append("=`").append(plain).append("`");
        }

        if (area.markups != null && !area.markups.isEmpty()) {
            hb.append(", ").append(MARKUPS).append("=[");
            for (Markup_V002 markup : area.markups) {
                hb.append("(").append(markup.from).append(",").append(markup.to)
                  .append(",").append(markup.type.name());
                if (markup.changeset != null && !markup.changeset.isEmpty()) {
                    hb.append(",").append(markup.changeset);
                }
                hb.append(")");
            }
            hb.append("]");
        }

        return hb.toString();
    }

    // ---- EditContainer head: areas[0] inline ----

    private String editContainerHead(EditorContentModel_V002 container) {
        if (!hasContent(container)) {
            return "``";
        }
        AbstractEditAreaModel_V002 firstArea = container.areas.get(0);
        if (firstArea instanceof TextEditAreaModel_V002 textArea) {
            return htmlContent(textArea);
        }
        return "``";
    }

    // ---- EditContainer tail: areas[fromIndex..n] in block ----

    private void appendEditContainerTail(EditorContentModel_V002 container, int fromIndex) {
        if (container == null || container.areas == null) {
            return;
        }
        List<AbstractEditAreaModel_V002> areas = container.areas;
        int i = fromIndex;
        while (i < areas.size()) {
            AbstractEditAreaModel_V002 area = areas.get(i);
            if (area instanceof ListItemEditAreaModel_V002 listItem) {
                boolean ordered = listItem.ordered;
                blockOpen(LIST, ORDERED + "=" + ordered);
                while (i < areas.size() &&
                       areas.get(i) instanceof ListItemEditAreaModel_V002 li &&
                       li.ordered == ordered) {
                    appendListItem(li);
                    i++;
                }
                blockClose();
            } else if (area instanceof TextEditAreaModel_V002 textArea) {
                sb.append(indent()).append(TEXT).append("(").append(htmlContent(textArea)).append(")\n");
                i++;
            } else if (area instanceof TableEditAreaModel_V002 tableArea) {
                appendTable(tableArea);
                i++;
            } else if (area instanceof ImageEditAreaModel_V002 imageArea) {
                appendImage(imageArea);
                i++;
            } else {
                i++;
            }
        }
    }

    // ---- List item ----

    private void appendListItem(ListItemEditAreaModel_V002 item) {
        boolean hasExtraAreas = hasContent(item.content) && item.content.areas.size() > 1;
        if (hasExtraAreas) {
            blockOpen(ITEM, editContainerHead(item.content), changeAnno(item.changeInfo));
            appendEditContainerTail(item.content, 1);
            blockClose();
        }
        else {
            sb.append(indent()).append(ITEM).append("(").append(editContainerHead(item.content));
            String anno = changeAnno(item.changeInfo);
            if (anno != null) {
                sb.append(", ").append(anno);
            }
            sb.append(")\n");
        }
    }

    // ---- Table ----

    private void appendTable(TableEditAreaModel_V002 tableArea) {
        String cols = null;
        if (tableArea.columnsWidthPercent != null && !tableArea.columnsWidthPercent.isEmpty()) {
            StringBuilder c = new StringBuilder(COLS + "=[");
            for (int i = 0; i < tableArea.columnsWidthPercent.size(); i++) {
                if (i > 0) { c.append(", "); }
                c.append(tableArea.columnsWidthPercent.get(i)).append("%");
            }
            cols = c.append("]").toString();
        }
        blockOpen(TABLE, WIDTH + "=" + tableArea.tableWidthPercent + "%", cols);
        if (tableArea.cells != null) {
            for (List<EditorContentModel_V002> row : tableArea.cells) {
                appendTableRow(row);
            }
        }
        blockClose();
    }

    private void appendTableRow(List<EditorContentModel_V002> row) {
        sb.append(indent()).append(ROW).append(" { ");
        for (int i = 0; i < row.size(); i++) {
            if (i > 0) { sb.append(" | "); }
            appendCell(row.get(i));
        }
        sb.append(" }\n");
    }

    private void appendCell(EditorContentModel_V002 cell) {
        boolean isSimple = cell.areas != null && cell.areas.size() == 1
                           && cell.areas.get(0) instanceof TextEditAreaModel_V002;
        if (isSimple) {
            sb.append(CELL).append("(").append(editContainerHead(cell)).append(")");
        }
        else {
            blockOpen(CELL, editContainerHead(cell));
            appendEditContainerTail(cell, 1);
            blockClose();
        }
    }

    // ---- Image ----

    private void appendImage(ImageEditAreaModel_V002 imageArea) {
        double scale = Math.round((double) imageArea.individualScalePercent * 10000.0) / 100.0;
        String scaleStr = String.format(java.util.Locale.US, "%.2f", scale).replaceAll("\\.?0+$", "");
        String type = imageArea.imageType != null ? imageArea.imageType : "png";
        String base64 = imageArea.imageData != null ? Base64.getEncoder().encodeToString(imageArea.imageData) : "";
        sb.append(indent()).append(IMAGE).append("(").append(SCALE).append("=").append(scaleStr).append("%, ").append(TYPE).append("=").append(type)
          .append(") { [base64:").append(base64).append("] }\n");
    }

    // ---- Change annotation ----

    private String changeAnno(ChangeInfoModel_V002 info) {
        if (info == null || info.changetype == null) {
            return null;
        }
        String changeType;
        if (info.changetype == Aenderungsart.Hinzugefuegt) {
            changeType = "added";
        } else if (info.changetype == Aenderungsart.Geloescht) {
            changeType = "removed";
        } else {
            return null;
        }
        String cs = info.changeset != null ? info.changeset : "yellow";
        return CHANGE + "=(" + changeType + ", " + cs + ")";
    }

    // ---- Step number ----

    private String stepNum(AbstractStepModel_V002 step) {
        return step.stepNumber != null ? step.stepNumber : "?";
    }

    private String stepId(AbstractStepModel_V002 step) {
        return AbstractStepModel_V002.normalizeId(step.id);
    }

    // ---- Steps ----

    private void appendSteps(StepSequenceModel_V002 seq, Map<String, String> idToNum) {
        if (seq == null || seq.steps == null) {
            return;
        }
        for (AbstractStepModel_V002 step : seq.steps) {
            appendStep(step, idToNum);
        }
    }

    private void appendStep(AbstractStepModel_V002 step, Map<String, String> idToNum) {
        if (step instanceof BreakStepModel_V002) {
            appendLeafStep(BREAK, step);
        } else if (step instanceof DoWhileStepModel_V002 doWhile) {
            appendLoopStep(DO_WHILE, doWhile.loopSequence, step, idToNum, false,
                BAR_WIDTH + "=" + doWhile.barWidth);
        } else if (step instanceof WhileStepModel_V002 whileStep) {
            appendLoopStep(WHILE, whileStep.loopSequence, step, idToNum, true,
                BAR_WIDTH + "=" + whileStep.barWidth);
        } else if (step instanceof IfElseStepModel_V002 ifElse) {
            appendIfElseStep(ifElse, idToNum);
        } else if (step instanceof IfStepModel_V002 ifStep) {
            appendIfStep(ifStep, idToNum);
        } else if (step instanceof CaseStepModel_V002 caseStep) {
            appendCaseStep(caseStep, idToNum);
        } else if (step instanceof SubsequenceStepModel_V002 subseq) {
            appendSubsequenceStep(subseq, idToNum);
        } else {
            // SimpleStepModel_V002, SourceStepModel_V002, and any unknown types
            appendLeafStep(SIMPLE, step);
        }
    }

    private void appendLeafStep(ModelKeyword_V002 keyword, AbstractStepModel_V002 step) {
        boolean hasExtraAreas = hasContent(step.content) && step.content.areas.size() > 1;
        if (hasExtraAreas) {
            blockOpen(keyword, stepNum(step), stepId(step), editContainerHead(step.content), changeAnno(step.changeInfo));
            appendEditContainerTail(step.content, 1);
            blockClose();
        } else {
            block(keyword, stepNum(step), stepId(step), editContainerHead(step.content), changeAnno(step.changeInfo));
        }
    }

    private void appendLoopStep(ModelKeyword_V002 keyword, StepSequenceModel_V002 loopSeq,
                                AbstractStepModel_V002 step,
                                Map<String, String> idToNum, boolean withCatch, String extraParam) {
        blockOpen(keyword, stepNum(step), stepId(step), editContainerHead(step.content), extraParam);
        appendEditContainerTail(step.content, 1);
        appendSteps(loopSeq, idToNum);
        if (withCatch && loopSeq != null) {
            appendCatchArea(loopSeq.catchArea, idToNum);
        }
        blockClose();
    }

    private void appendIfElseStep(IfElseStepModel_V002 step, Map<String, String> idToNum) {
        blockOpen(IF_ELSE,
          stepNum(step),
          stepId(step),
          editContainerHead(step.content),
          String.format(java.util.Locale.US, IF_RATIO + "=%.2f%%", step.ifWidthRatio * 100)
        );
        appendEditContainerTail(step.content, 1);
        appendBranch(IF_BRANCH, step.ifSequence, idToNum, true);
        appendBranch(ELSE_BRANCH, step.elseSequence, idToNum, true);
        blockClose();
    }

    private void blockBegin(ModelKeyword_V002 blockType, String... parameters) {
        String parametersString = Arrays
          .stream(parameters)
          .filter(Objects::nonNull)
          .collect(Collectors.joining(", "));

        sb.append(indent()).append(blockType);
        if (!parametersString.isEmpty()) {
            sb.append("(").append(parametersString).append(")");
        }
    }

    private void blockOpen(ModelKeyword_V002 blockType, String... parameters) {
        blockBegin(blockType, parameters);
        sb.append(" {\n");
        indentionLevel++;
    }

    private void blockClose() {
        indentionLevel--;
        sb.append(indent()).append("}\n");
    }

    private void block(ModelKeyword_V002 blockType, String... parameters) {
        blockBegin(blockType, parameters);
        sb.append(";\n");
    }

    private void appendIfStep(IfStepModel_V002 step, Map<String, String> idToNum) {
        blockOpen(IF,
          stepNum(step),
          stepId(step),
          editContainerHead(step.content),
          EMPTY_WIDTH + "=" + step.emptyWidth
        );

        appendEditContainerTail(step.content, 1);
        appendBranch(IF_BRANCH, step.ifSequence, idToNum, true);

        blockClose();
    }

    private void appendCaseStep(CaseStepModel_V002 step, Map<String, String> idToNum) {
        String cols = null;
        if (step.columnWidthRatios != null && !step.columnWidthRatios.isEmpty()) {
            StringBuilder c = new StringBuilder(COLS + "=[");
            for (int i = 0; i < step.columnWidthRatios.size(); i++) {
                if (i > 0) { c.append(", "); }
                c.append(String.format(java.util.Locale.US, "%.2f", step.columnWidthRatios.get(i) * 100)).append("%");
            }
            cols = c.append("]").toString();
        }
        blockOpen(CASE, stepNum(step), stepId(step), editContainerHead(step.content), cols);
        appendEditContainerTail(step.content, 1);
        appendBranch(DEFAULT_BRANCH, step.defaultSequence, idToNum, false);
        if (step.caseSequences != null) {
            for (BranchSequenceModel_V002 caseSeq : step.caseSequences) {
                appendBranch(CASE_BRANCH, caseSeq, idToNum, false);
            }
        }
        blockClose();
    }

    private void appendSubsequenceStep(SubsequenceStepModel_V002 step, Map<String, String> idToNum) {
        blockOpen(SUBSEQUENCE,
          stepNum(step),
          stepId(step),
          editContainerHead(step.content),
          step.flatNumbering ? FLAT + "=true" : null
        );
        appendEditContainerTail(step.content, 1);
        appendSteps(step.subsequence, idToNum);
        appendCatchArea(step.subsequence != null ? step.subsequence.catchArea : null, idToNum);
        blockClose();
    }

    private void appendBranch(ModelKeyword_V002 keyword, BranchSequenceModel_V002 branch,
                               Map<String, String> idToNum, boolean withCatch) {
        if (branch == null) {
            return;
        }
        blockOpen(keyword, editContainerHead(branch.heading));
        appendEditContainerTail(branch.heading, 1);
        appendSteps(branch, idToNum);
        if (withCatch) {
            appendCatchArea(branch.catchArea, idToNum);
        }
        blockClose();
    }

    // ---- Catch area ----

    private void appendCatchArea(CatchAreaModel_V002 catchArea, Map<String, String> idToNum) {
        if (catchArea == null || catchArea.catchSequences == null || catchArea.catchSequences.isEmpty()) {
            return;
        }
        for (CatchSequenceModel_V002 catchSeq : catchArea.catchSequences) {
            String breakStepNum = idToNum.getOrDefault(catchSeq.id, "?");
            blockOpen(CATCH, breakStepNum, editContainerHead(catchSeq.heading));
            appendEditContainerTail(catchSeq.heading, 1);
            if (catchSeq.coCatches != null) {
                for (CoCatchModel_V002 coCatch : catchSeq.coCatches) {
                    String coCatchNum = idToNum.getOrDefault(coCatch.breakStepId, "?");
                    block(CO_CATCH, coCatchNum, editContainerHead(coCatch.heading));
                }
            }
            appendSteps(catchSeq, idToNum);
            blockClose();
        }
    }
}
