package specman.model.v002.io;

import specman.Aenderungsart;
import specman.SpecmanVersion;
import specman.model.v002.AbstractEditAreaModel_V002;
import specman.model.v002.AbstractStepModel_V002;
import specman.model.v002.BranchSequenceModel_V002;
import specman.model.v002.BreakStepModel_V002;
import specman.model.v002.CaseStepModel_V002;
import specman.model.v002.CatchAreaModel_V002;
import specman.model.v002.CatchSequenceModel_V002;
import specman.model.v002.ChangeInfoModel_V002;
import specman.model.v002.CoCatchModel_V002;
import specman.model.v002.DiagramModel_V002;
import specman.model.v002.DoWhileStepModel_V002;
import specman.model.v002.PdfExportOptionsModel_V002;
import specman.model.v002.EditorContentModel_V002;
import specman.model.v002.IfElseStepModel_V002;
import specman.model.v002.IfStepModel_V002;
import specman.model.v002.ImageEditAreaModel_V002;
import specman.model.v002.ListItemEditAreaModel_V002;
import specman.model.v002.Markup_V002;
import specman.model.v002.StepSequenceModel_V002;
import specman.model.v002.SubsequenceStepModel_V002;
import specman.model.v002.TableEditAreaModel_V002;
import specman.model.v002.TextEditAreaModel_V002;
import specman.model.v002.WhileStepModel_V002;

import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** Serializes a {@link DiagramModel_V002} to the SpecmanModel_V002 text format (.nsd). */
public class ModelSerializer_V002 {

    private static final Pattern BODY_PATTERN = Pattern.compile("<body>([\\s\\S]*?)</body>");

    /** Serializes a DiagramModel_V002 to SpecmanModel_V002 text format. */
    public String serialize(DiagramModel_V002 model) {
        Map<String, String> idToStepNumber = buildIdToStepNumber(model);
        StringBuilder sb = new StringBuilder();

        // First line: JSON envelope — read by Jackson, skipped by ANTLR
        sb.append("// {\"specmanVersion\":\"").append(SpecmanVersion.getVersion())
          .append("\",\"modelType\":\"").append(DiagramModel_V002.class.getName()).append("\"}\n");
        sb.append("// Specman: ").append(model.name != null ? model.name : "").append("\n");
        sb.append("// Format defined by grammar: SpecmanModel_V002.g4\n");
        sb.append("// AI AGENTS: plain=`...` fields are generated by Specman during validation — ignore them.\n");
        sb.append("// AI AGENTS: markups=[...] fields are managed by Specman — ignore them.\n");
        sb.append("// AI AGENTS: image(...) { [base64:...] } blocks — ignore them.\n");

        appendSettings(sb, model);

        if (hasContent(model.intro)) {
            sb.append("\nintro(").append(editContainerHead(model.intro)).append(") {\n");
            appendEditContainerTail(sb, model.intro, "    ", 1);
            sb.append("}\n");
        }

        sb.append("\nsequence main {\n");
        appendSteps(sb, model.mainSequence, "    ", idToStepNumber);
        appendCatchArea(sb, model.mainSequence != null ? model.mainSequence.catchArea : null, "    ", idToStepNumber);
        sb.append("}\n");

        if (hasContent(model.outro)) {
            sb.append("\noutro(").append(editContainerHead(model.outro)).append(") {\n");
            appendEditContainerTail(sb, model.outro, "    ", 1);
            sb.append("}\n");
        }

        return sb.toString();
    }

    private boolean hasContent(EditorContentModel_V002 container) {
        return container != null && container.areas != null && !container.areas.isEmpty();
    }

    private void appendSettings(StringBuilder sb, DiagramModel_V002 model) {
        sb.append("\nsettings {\n");
        sb.append("    width: ").append(model.width).append("\n");
        sb.append("    zoom: ").append(model.zoomFactor).append("\n");
        sb.append("    changeModeEnabled: ").append(model.changeModeEnabled).append("\n");
        sb.append("    changeSetName: ").append(model.changeSetName != null ? model.changeSetName : "yellow").append("\n");
        if (model.pdfExportOptions != null) {
            PdfExportOptionsModel_V002 pdf = model.pdfExportOptions;
            sb.append("    pdfOptions {\n");
            if (pdf.filename != null) {
                sb.append("        filename: `").append(pdf.filename).append("`\n");
            }
            if (pdf.modelFilename != null) {
                sb.append("        modelFilename: `").append(pdf.modelFilename).append("`\n");
            }
            if (pdf.pageSize != null) {
                sb.append("        pageSize: ").append(pdf.pageSize).append("\n");
            }
            sb.append("        portrait: ").append(pdf.portrait).append("\n");
            sb.append("        paging: ").append(pdf.paging).append("\n");
            sb.append("    }\n");
        }
        sb.append("}\n");
    }

    // ---- id → stepNumber map ----

    private Map<String, String> buildIdToStepNumber(DiagramModel_V002 model) {
        Map<String, String> map = new LinkedHashMap<>();
        for (AbstractStepModel_V002 step : model.queryAllSteps()) {
            if (step.id != null && step.stepNumber != null) {
                map.put(step.id, step.stepNumber);
            }
        }
        return map;
    }

    // ---- HTML body extraction ----

    private String extractBodyHtml(String text) {
        if (text == null) {
            return "";
        }
        Matcher m = BODY_PATTERN.matcher(text);
        if (m.find()) {
            return m.group(1).trim();
        }
        return text.trim();
    }

    private String escapeBackticks(String text) {
        if (text == null) {
            return "";
        }
        return text.replace("`", "'");
    }

    // ---- htmlContent: `html`, plain=`...`, markups=[...] ----

    private String htmlContent(TextEditAreaModel_V002 area) {
        StringBuilder sb = new StringBuilder();
        sb.append("`").append(escapeBackticks(extractBodyHtml(area.text))).append("`");

        if (area.plainText != null && !area.plainText.isEmpty()) {
            String plain = escapeBackticks(area.plainText.replaceAll("^\\n", ""));
            sb.append(", plain=`").append(plain).append("`");
        }

        if (area.markups != null && !area.markups.isEmpty()) {
            sb.append(", markups=[");
            for (Markup_V002 markup : area.markups) {
                sb.append("(").append(markup.from).append(",").append(markup.to)
                  .append(",").append(markup.type.name());
                if (markup.changeset != null && !markup.changeset.isEmpty()) {
                    sb.append(",").append(markup.changeset);
                }
                sb.append(")");
            }
            sb.append("]");
        }

        return sb.toString();
    }

    // ---- EditContainer head: areas[0] inline ----

    private String editContainerHead(EditorContentModel_V002 container) {
        if (!hasContent(container)) {
            return "``";
        }
        AbstractEditAreaModel_V002 firstArea = container.areas.get(0);
        if (firstArea instanceof TextEditAreaModel_V002 textArea) {
            return htmlContent(textArea);
        }
        return "``";
    }

    // ---- EditContainer tail: areas[fromIndex..n] in block ----

    private void appendEditContainerTail(StringBuilder sb, EditorContentModel_V002 container, String indent, int fromIndex) {
        if (container == null || container.areas == null) {
            return;
        }
        List<AbstractEditAreaModel_V002> areas = container.areas;
        int i = fromIndex;
        while (i < areas.size()) {
            AbstractEditAreaModel_V002 area = areas.get(i);
            if (area instanceof ListItemEditAreaModel_V002 listItem) {
                boolean ordered = listItem.ordered;
                sb.append(indent).append("list(ordered=").append(ordered).append(") {\n");
                while (i < areas.size() &&
                       areas.get(i) instanceof ListItemEditAreaModel_V002 li &&
                       li.ordered == ordered) {
                    appendListItem(sb, li, indent + "    ");
                    i++;
                }
                sb.append(indent).append("}\n");
            } else if (area instanceof TextEditAreaModel_V002 textArea) {
                sb.append(indent).append("text(").append(htmlContent(textArea)).append(")\n");
                i++;
            } else if (area instanceof TableEditAreaModel_V002 tableArea) {
                appendTable(sb, tableArea, indent);
                i++;
            } else if (area instanceof ImageEditAreaModel_V002 imageArea) {
                appendImage(sb, imageArea, indent);
                i++;
            } else {
                i++;
            }
        }
    }

    // ---- List item ----

    private void appendListItem(StringBuilder sb, ListItemEditAreaModel_V002 item, String indent) {
        sb.append(indent).append("item(").append(editContainerHead(item.content)).append(")");

        String anno = changeAnno(item.changeInfo);
        if (!anno.isEmpty()) {
            sb.append(" ").append(anno);
        }

        boolean hasExtraAreas = hasContent(item.content) && item.content.areas.size() > 1;
        if (hasExtraAreas) {
            sb.append(" {\n");
            appendEditContainerTail(sb, item.content, indent + "    ", 1);
            sb.append(indent).append("}");
        }

        sb.append("\n");
    }

    // ---- Table ----

    private void appendTable(StringBuilder sb, TableEditAreaModel_V002 tableArea, String indent) {
        sb.append(indent).append("table(width=").append(tableArea.tableWidthPercent).append("%");
        if (tableArea.columnsWidthPercent != null && !tableArea.columnsWidthPercent.isEmpty()) {
            sb.append(", cols=[");
            for (int i = 0; i < tableArea.columnsWidthPercent.size(); i++) {
                if (i > 0) {
                    sb.append(", ");
                }
                sb.append(tableArea.columnsWidthPercent.get(i)).append("%");
            }
            sb.append("]");
        }
        sb.append(") {\n");
        if (tableArea.cells != null) {
            for (List<EditorContentModel_V002> row : tableArea.cells) {
                appendTableRow(sb, row, indent + "    ");
            }
        }
        sb.append(indent).append("}\n");
    }

    private void appendTableRow(StringBuilder sb, List<EditorContentModel_V002> row, String indent) {
        sb.append(indent).append("row { ");
        boolean first = true;
        for (EditorContentModel_V002 cell : row) {
            if (!first) {
                sb.append(" | ");
            }
            first = false;
            boolean isSimple = cell.areas != null && cell.areas.size() == 1 && cell.areas.get(0) instanceof TextEditAreaModel_V002;
            if (isSimple) {
                sb.append("cell(").append(editContainerHead(cell)).append(")");
            } else {
                sb.append("cell(").append(editContainerHead(cell)).append(") {\n");
                appendEditContainerTail(sb, cell, indent + "    ", 1);
                sb.append(indent).append("}");
            }
        }
        sb.append(" }\n");
    }

    // ---- Image ----

    private void appendImage(StringBuilder sb, ImageEditAreaModel_V002 imageArea, String indent) {
        double scale = Math.round((double) imageArea.individualScalePercent * 10000.0) / 100.0;
        String scaleStr = String.format(java.util.Locale.US, "%.2f", scale).replaceAll("\\.?0+$", "");
        String type = imageArea.imageType != null ? imageArea.imageType : "png";
        String base64 = imageArea.imageData != null ? Base64.getEncoder().encodeToString(imageArea.imageData) : "";
        sb.append(indent).append("image(scale=").append(scaleStr).append("%, type=").append(type)
          .append(") { [base64:").append(base64).append("] }\n");
    }

    // ---- Change annotation ----

    private String changeAnno(ChangeInfoModel_V002 info) {
        if (info == null || info.changetype == null) {
            return "";
        }
        String changeType;
        if (info.changetype == Aenderungsart.Hinzugefuegt) {
            changeType = "added";
        } else if (info.changetype == Aenderungsart.Geloescht) {
            changeType = "removed";
        } else {
            return "";
        }
        String cs = info.changeset != null ? info.changeset : "yellow";
        return "[change=" + changeType + ", changeset=" + cs + "]";
    }

    // ---- Step number ----

    private String stepNum(AbstractStepModel_V002 step) {
        return step.stepNumber != null ? step.stepNumber : "?";
    }

    private String stepId(AbstractStepModel_V002 step) {
        return AbstractStepModel_V002.normalizeId(step.id);
    }

    // ---- Steps ----

    private void appendSteps(StringBuilder sb, StepSequenceModel_V002 seq, String indent, Map<String, String> idToNum) {
        if (seq == null || seq.steps == null) {
            return;
        }
        for (AbstractStepModel_V002 step : seq.steps) {
            appendStep(sb, step, indent, idToNum);
        }
    }

    private void appendStep(StringBuilder sb, AbstractStepModel_V002 step, String indent, Map<String, String> idToNum) {
        if (step instanceof BreakStepModel_V002) {
            appendLeafStep(sb, "break", step, indent);
        } else if (step instanceof DoWhileStepModel_V002 doWhile) {
            appendLoopStep(sb, "doWhile", doWhile.loopSequence, step, indent, idToNum, false);
        } else if (step instanceof WhileStepModel_V002 whileStep) {
            appendLoopStep(sb, "while", whileStep.loopSequence, step, indent, idToNum, true);
        } else if (step instanceof IfElseStepModel_V002 ifElse) {
            appendIfElseStep(sb, ifElse, indent, idToNum);
        } else if (step instanceof IfStepModel_V002 ifStep) {
            appendIfStep(sb, ifStep, indent, idToNum);
        } else if (step instanceof CaseStepModel_V002 caseStep) {
            appendCaseStep(sb, caseStep, indent, idToNum);
        } else if (step instanceof SubsequenceStepModel_V002 subseq) {
            appendSubsequenceStep(sb, subseq, indent, idToNum);
        } else {
            // SimpleStepModel_V002, SourceStepModel_V002, and any unknown types
            appendLeafStep(sb, "simple", step, indent);
        }
    }

    private void appendLeafStep(StringBuilder sb, String keyword, AbstractStepModel_V002 step, String indent) {
        String head = editContainerHead(step.content);
        String anno = changeAnno(step.changeInfo);
        boolean hasExtraAreas = hasContent(step.content) && step.content.areas.size() > 1;

        sb.append(indent).append(keyword).append("(")
          .append(stepNum(step)).append(", ")
          .append(stepId(step)).append(", ")
          .append(head).append(")");

        if (!anno.isEmpty()) {
            sb.append(" ").append(anno);
        }

        if (hasExtraAreas) {
            sb.append(" {\n");
            appendEditContainerTail(sb, step.content, indent + "    ", 1);
            sb.append(indent).append("}\n");
        } else {
            sb.append(";\n");
        }
    }

    private void appendLoopStep(StringBuilder sb, String keyword, StepSequenceModel_V002 loopSeq,
                                AbstractStepModel_V002 step, String indent,
                                Map<String, String> idToNum, boolean withCatch) {
        sb.append(indent).append(keyword).append("(")
          .append(stepNum(step)).append(", ")
          .append(stepId(step)).append(", ")
          .append(editContainerHead(step.content)).append(") {\n");

        appendEditContainerTail(sb, step.content, indent + "    ", 1);
        appendSteps(sb, loopSeq, indent + "    ", idToNum);
        if (withCatch && loopSeq != null) {
            appendCatchArea(sb, loopSeq.catchArea, indent + "    ", idToNum);
        }

        sb.append(indent).append("}\n");
    }

    private void appendIfElseStep(StringBuilder sb, IfElseStepModel_V002 step, String indent, Map<String, String> idToNum) {
        sb.append(indent).append("ifElse(")
          .append(stepNum(step)).append(", ")
          .append(stepId(step)).append(", ")
          .append(editContainerHead(step.content)).append(") {\n");

        appendEditContainerTail(sb, step.content, indent + "    ", 1);
        appendBranch(sb, "if_branch", step.ifSequence, indent + "    ", idToNum, true);
        appendBranch(sb, "else_branch", step.elseSequence, indent + "    ", idToNum, true);

        sb.append(indent).append("}\n");
    }

    private void appendIfStep(StringBuilder sb, IfStepModel_V002 step, String indent, Map<String, String> idToNum) {
        sb.append(indent).append("if(")
          .append(stepNum(step)).append(", ")
          .append(stepId(step)).append(", ")
          .append(editContainerHead(step.content)).append(") {\n");

        appendEditContainerTail(sb, step.content, indent + "    ", 1);
        appendBranch(sb, "if_branch", step.ifSequence, indent + "    ", idToNum, true);

        sb.append(indent).append("}\n");
    }

    private void appendCaseStep(StringBuilder sb, CaseStepModel_V002 step, String indent, Map<String, String> idToNum) {
        sb.append(indent).append("case(")
          .append(stepNum(step)).append(", ")
          .append(stepId(step)).append(", ")
          .append(editContainerHead(step.content)).append(") {\n");

        appendEditContainerTail(sb, step.content, indent + "    ", 1);
        appendBranch(sb, "default_branch", step.defaultSequence, indent + "    ", idToNum, false);

        if (step.caseSequences != null) {
            for (BranchSequenceModel_V002 caseSeq : step.caseSequences) {
                appendBranch(sb, "case_branch", caseSeq, indent + "    ", idToNum, false);
            }
        }

        sb.append(indent).append("}\n");
    }

    private void appendSubsequenceStep(StringBuilder sb, SubsequenceStepModel_V002 step, String indent, Map<String, String> idToNum) {
        sb.append(indent).append("subsequence(")
          .append(stepNum(step)).append(", ")
          .append(stepId(step)).append(", ")
          .append(editContainerHead(step.content)).append(")");

        if (step.flatNumbering) {
            sb.append(", flat=true");
        }

        sb.append(" {\n");
        appendEditContainerTail(sb, step.content, indent + "    ", 1);
        appendSteps(sb, step.subsequence, indent + "    ", idToNum);
        appendCatchArea(sb, step.subsequence != null ? step.subsequence.catchArea : null, indent + "    ", idToNum);
        sb.append(indent).append("}\n");
    }

    private void appendBranch(StringBuilder sb, String keyword, BranchSequenceModel_V002 branch,
                              String indent, Map<String, String> idToNum, boolean withCatch) {
        if (branch == null) {
            return;
        }
        sb.append(indent).append(keyword).append("(")
          .append(editContainerHead(branch.heading)).append(") {\n");

        appendEditContainerTail(sb, branch.heading, indent + "    ", 1);
        appendSteps(sb, branch, indent + "    ", idToNum);

        if (withCatch) {
            appendCatchArea(sb, branch.catchArea, indent + "    ", idToNum);
        }

        sb.append(indent).append("}\n");
    }

    // ---- Catch area ----

    private void appendCatchArea(StringBuilder sb, CatchAreaModel_V002 catchArea, String indent, Map<String, String> idToNum) {
        if (catchArea == null || catchArea.catchSequences == null || catchArea.catchSequences.isEmpty()) {
            return;
        }
        for (CatchSequenceModel_V002 catchSeq : catchArea.catchSequences) {
            String breakStepNum = idToNum.getOrDefault(catchSeq.id, "?");
            sb.append(indent).append("catch(")
              .append(breakStepNum).append(", ")
              .append(editContainerHead(catchSeq.heading)).append(") {\n");

            appendEditContainerTail(sb, catchSeq.heading, indent + "    ", 1);

            if (catchSeq.coCatches != null) {
                for (CoCatchModel_V002 coCatch : catchSeq.coCatches) {
                    String coCatchNum = idToNum.getOrDefault(coCatch.breakStepId, "?");
                    sb.append(indent).append("    coCatch(")
                      .append(coCatchNum).append(", ")
                      .append(editContainerHead(coCatch.heading)).append(");\n");
                }
            }

            appendSteps(sb, catchSeq, indent + "    ", idToNum);
            sb.append(indent).append("}\n");
        }
    }
}
