grammar SpecmanModel_V002;
// ============================================================
// SpecmanModel_V002 grammar — Specman V2 model text format.
//
// A V2 model file is a self-contained, agent-editable representation
// of a Specman NSD diagram. It maps 1:1 to DiagramModel_V002 and
// its nested V002 classes.
//
// File structure:
//   Line 1: JSON envelope comment — read by LoadDiagrammSpecmanOp.readMeta()
//           via Jackson; skipped transparently by the ANTLR parser.
//           Format: // {"specmanVersion":"1.3.0","modelType":"specman.model.v002.DiagramModel_V002"}
//   Rest:   Model content parsed by this grammar.
//
// Key conventions:
//   stepNum          — dot-separated integers with optional letter suffix
//                      (e.g. 1, 2.3, 3.2.4.2b). Managed by Specman --sanitize;
//                      agents may use any unique placeholder for new steps.
//   stepId           — 8 lower-case hex characters, Git-short-hash style
//                      (e.g. 09a3df2d). Generated by AbstractStepModel_V002.generateId().
//   htmlText         — backtick-delimited HTML body content (no <html>/<body> wrapper).
//                      Must not contain literal backtick characters.
//   plain=           — plain-text rendering of the preceding htmlText; generated by
//                      Specman --sanitize. Agents must not write or update this field.
//   markups=         — character-level markup spans; managed by Specman. Agents may
//                      write or update this field if capable.
//   image            — inline base64 image data. Agents must ignore image blocks.
//
// EditContainer pattern (EditorContentModel_V002):
//   Wherever the model contains an EditorContentModel, the format
//   applies a consistent two-part representation:
//     editContainerHead — the first area (always a TextEditArea), written inline
//                         as an htmlContent parameter.
//     editContainerTail — any further areas (list, text, table, image), written
//                         at the start of the enclosing { } block.
//   This pattern appears in step content, branch headings, catch headings,
//   list item content, table cell content, intro, and outro.
// ============================================================

// ============================================================
// Parser rules
// ============================================================

diagram
    : settings? intro? mainSequence outro? EOF
    ;

// Diagram-level settings (DiagramModel_V002 scalar fields + PdfExportOptionsModel_V002).
// All entries are optional; absent entries fall back to defaults when parsing.
settings
    : 'settings' '{' settingEntry* '}'
    ;

settingEntry
    : 'width'             ':' STEP_NUM
    | 'zoom'              ':' STEP_NUM
    | 'changeModeEnabled' ':' boolVal
    | 'changeSetName'     ':' ID
    | 'pdfOptions'        '{' pdfOptionEntry* '}'
    ;

pdfOptionEntry
    : 'filename'      ':' BACKTICK_STRING
    | 'modelFilename' ':' BACKTICK_STRING
    | 'pageSize'      ':' ID
    | 'portrait'      ':' boolVal
    | 'paging'        ':' boolVal
    ;

// Intro and outro are EditorContentModel_V002 — full EditContainer pattern.
intro
    : 'intro' '(' editContainerHead ')' '{' editContainerTail '}'
    ;

outro
    : 'outro' '(' editContainerHead ')' '{' editContainerTail '}'
    ;

mainSequence
    : 'mainSequence' '{' step+ catchBlock* '}'
    ;

// --- Steps ---
// Each step holds an EditorContentModel_V002 as its content.
// editContainerHead is the inline first TextEditArea.
// editContainerTail holds any further areas at the top of the { } block.

step
    : simpleStep
    | breakStep
    | whileStep
    | doWhileStep
    | ifElseStep
    | ifStep
    | caseStep
    | subsequenceStep
    ;

// change=(type, changeset) is an optional inline parameter for ChangeInfoModel_V002.
simpleStep
    : 'simple' '(' stepNum ',' stepId ',' editContainerHead (',' changeParam)? ')' (';' | '{' editContainerTail '}')
    ;

// UI convention: break text is single-line, but the model allows extra areas.
breakStep
    : 'break' '(' stepNum ',' stepId ',' editContainerHead (',' changeParam)? ')' (';' | '{' editContainerTail '}')
    ;

// barWidth preserves the user-set width of the loop bar in pixels.
whileStep
    : 'while' '(' stepNum ',' stepId ',' editContainerHead (',' 'barWidth' '=' STEP_NUM)? ')' '{' editContainerTail step+ catchBlock* '}'
    ;

doWhileStep
    : 'doWhile' '(' stepNum ',' stepId ',' editContainerHead (',' 'barWidth' '=' STEP_NUM)? ')' '{' editContainerTail step+ '}'
    ;

// ifRatio preserves the user-set width ratio of the if-branch vs. total (as percentage).
ifElseStep
    : 'ifElse' '(' stepNum ',' stepId ',' editContainerHead (',' 'ifRatio' '=' PERCENT)? ')' '{' editContainerTail ifBranch elseBranch '}'
    ;

// emptyWidth preserves the user-set width of the empty else area in pixels.
ifStep
    : 'if' '(' stepNum ',' stepId ',' editContainerHead (',' 'emptyWidth' '=' STEP_NUM)? ')' '{' editContainerTail ifBranch '}'
    ;

// editContainerTail covers extra areas of the condition content (e.g. a condition list).
// Requires exactly one defaultBranch and at least two caseBranches.
// cols=[...] preserves the user-set column width ratios (one entry per branch incl. default).
caseStep
    : 'case' '(' stepNum ',' stepId ',' editContainerHead (',' 'cols' '=' '[' PERCENT (',' PERCENT)* ']')? ')'
      '{' editContainerTail defaultBranch caseBranch caseBranch+ '}'
    ;

// flat=true preserves the flat-numbering flag as an inline parameter, consistent with other optionals.
subsequenceStep
    : 'subsequence' '(' stepNum ',' stepId ',' editContainerHead (',' 'flat' '=' 'true')? ')' '{' editContainerTail step+ catchBlock* '}'
    ;

// Branch headings are EditorContentModel_V002 — full EditContainer pattern.
ifBranch
    : 'if_branch' '(' editContainerHead ')' '{' editContainerTail step+ catchBlock* '}'
    ;

elseBranch
    : 'else_branch' '(' editContainerHead ')' '{' editContainerTail step+ catchBlock* '}'
    ;

defaultBranch
    : 'default_branch' '(' editContainerHead ')' '{' editContainerTail step+ '}'
    ;

caseBranch
    : 'case_branch' '(' editContainerHead ')' '{' editContainerTail step+ '}'
    ;

// Catch/coCatch headings are EditorContentModel_V002 — full EditContainer pattern.
catchBlock
    : 'catch' '(' stepNum ',' editContainerHead ')' '{' editContainerTail coCatch* step+ '}'
    ;

coCatch
    : 'coCatch' '(' stepNum ',' editContainerHead ')' ';'
    ;

// --- EditContainer building blocks ---

// The first TextEditArea of any EditorContentModel — always present, written inline.
editContainerHead
    : htmlContent
    ;

// The remaining areas[1..n] of an EditorContentModel — zero or more, written in the block.
// For intro/outro the full areas list is covered here (editContainerHead covers areas[0]).
editContainerTail
    : area*
    ;

// --- Content areas (AbstractEditAreaModel_V002 subtypes) ---

area
    : listBlock
    | textArea
    | tableBlock
    | imageBlock
    ;

// ListItemEditAreaModel_V002 — consecutive same-ordered items grouped into one block.
listBlock
    : 'list' '(' 'ordered' '=' boolVal ')' '{' listItem* '}'
    ;

// List item content is EditorContentModel_V002 — EditContainer pattern applies.
// Nested lists are not supported by Specman, so listBlock is excluded from the tail.
listItem
    : 'item' '(' editContainerHead (',' changeParam)? ')' ('{' listItemTail '}')?
    ;

// Restricted tail for list items: no nested listBlock per Specman constraint.
listItemTail
    : (textArea | tableBlock | imageBlock)*
    ;

// Intermediate TextEditAreaModel_V002 within a multi-area container.
textArea
    : 'text' '(' htmlContent ')'
    ;

// TableEditAreaModel_V002
tableBlock
    : 'table' '(' 'width' '=' PERCENT (',' 'cols' '=' '[' PERCENT (',' PERCENT)* ']')? ')' '{' tableRow* '}'
    ;

tableRow
    : 'row' '{' tableCell ('|' tableCell)* '}'
    ;

// Table cell is EditorContentModel_V002 — EditContainer pattern applies.
tableCell
    : 'cell' '(' editContainerHead ')'
    | 'cell' '(' editContainerHead ')' '{' editContainerTail '}'
    ;

// ImageEditAreaModel_V002 — agents must skip this block entirely.
imageBlock
    : 'image' '(' 'scale' '=' PERCENT ',' 'type' '=' ID ')' '{' BASE64_BLOCK '}'
    ;

// --- HTML content with optional Specman-managed metadata ---

// Maps to TextEditAreaModel_V002: text (htmlText), plainText (plain=), markups (markups=).
htmlContent
    : BACKTICK_STRING plainAttr? markupsAttr?
    ;

plainAttr
    : ',' 'plain' '=' BACKTICK_STRING
    ;

markupsAttr
    : ',' 'markups' '=' '[' markup* ']'
    ;

// Markup_V002: from, to, type, optional changeset name.
markup
    : '(' STEP_NUM ',' STEP_NUM ',' markupType (',' ID)? ')'
    ;

markupType
    : 'Changed'
    | 'Steplink'
    | 'ChangedSteplink'
    ;

// --- ChangeInfoModel_V002 as inline parameter ---

// change=(type, changeset) — inline, consistent with other optional parameters.
changeParam
    : 'change' '=' '(' changeType ',' ID ')'
    ;

changeType
    : 'added'
    | 'removed'
    | 'modified'
    ;

boolVal
    : 'true'
    | 'false'
    ;

// StepNumber — dot-separated integers, optional single lower-case letter suffix
// for agent-assigned placeholder numbers (e.g. 3.2.4.2b).
stepNum
    : STEP_NUM
    ;

// 8 lower-case hex characters (AbstractStepModel_V002.ID_LENGTH = 8).
stepId
    : STEP_ID
    ;

// ============================================================
// Lexer rules
// ============================================================

// Step ID: exactly 8 lower-case hex characters
STEP_ID     : [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f] ;

// Step number: 1, 2.3, 3.2.4.2b, 3.2.4.2b.1 (letter may appear mid-sequence)
STEP_NUM    : [0-9]+ [a-z]? ('.' [0-9]+ [a-z]?)* ;

// Percentage value, e.g. 100%, 39.07%
PERCENT     : [0-9]+ ('.' [0-9]+)? '%' ;

// Keywords — named so that SpecmanKeywords can reference them via the lexer VOCABULARY.
// Must be defined before ID so they take precedence over the general identifier rule.
KW_SIMPLE          : 'simple' ;
KW_BREAK           : 'break' ;
KW_WHILE           : 'while' ;
KW_DO_WHILE        : 'doWhile' ;
KW_IF_ELSE         : 'ifElse' ;
KW_IF              : 'if' ;
KW_CASE            : 'case' ;
KW_SUBSEQUENCE     : 'subsequence' ;
KW_MAIN_SEQUENCE   : 'mainSequence' ;
KW_INTRO           : 'intro' ;
KW_OUTRO           : 'outro' ;
KW_SETTINGS        : 'settings' ;
KW_IF_BRANCH       : 'if_branch' ;
KW_ELSE_BRANCH     : 'else_branch' ;
KW_DEFAULT_BRANCH  : 'default_branch' ;
KW_CASE_BRANCH     : 'case_branch' ;
KW_CATCH           : 'catch' ;
KW_CO_CATCH        : 'coCatch' ;
KW_LIST            : 'list' ;
KW_ITEM            : 'item' ;
KW_TABLE           : 'table' ;
KW_ROW             : 'row' ;
KW_CELL            : 'cell' ;
KW_IMAGE           : 'image' ;
KW_TEXT            : 'text' ;
KW_ORDERED         : 'ordered' ;
KW_FLAT            : 'flat' ;
KW_COLS            : 'cols' ;
KW_WIDTH           : 'width' ;
KW_ZOOM            : 'zoom' ;
KW_BAR_WIDTH       : 'barWidth' ;
KW_IF_RATIO        : 'ifRatio' ;
KW_EMPTY_WIDTH     : 'emptyWidth' ;
KW_PLAIN           : 'plain' ;
KW_MARKUPS         : 'markups' ;
KW_SCALE           : 'scale' ;
KW_TYPE            : 'type' ;
KW_CHANGE          : 'change' ;
KW_CHANGE_MODE     : 'changeModeEnabled' ;
KW_CHANGESET_NAME  : 'changeSetName' ;
KW_PDF_OPTIONS     : 'pdfOptions' ;
KW_FILENAME        : 'filename' ;
KW_MODEL_FILENAME  : 'modelFilename' ;
KW_PAGE_SIZE       : 'pageSize' ;
KW_PORTRAIT        : 'portrait' ;
KW_PAGING          : 'paging' ;

// Identifiers: changeset names (yellow, blue), image types (png)
ID          : [a-zA-Z][a-zA-Z0-9_-]* ;

// Backtick-delimited HTML content; must not contain literal backtick characters
BACKTICK_STRING : '`' ~'`'* '`' ;

// Complete [base64:...] block as a single token — prevents base64 chars from conflicting with ID
BASE64_BLOCK : '[' 'base64' ':' [a-zA-Z0-9+/]* '='* ']' ;

WS          : [ \t\r\n]+ -> skip ;

// First line: JSON envelope {"specmanVersion":...,"modelType":...} — read by Jackson, skipped by ANTLR
ENVELOPE_COMMENT : '//' [ \t]* '{' ~[\r\n]* -> skip ;

// Remaining comment lines: agent instructions, diagram name, etc.
LINE_COMMENT : '//' ~[\r\n]* -> skip ;
