package specman.suggest.github;

import javax.swing.*;
import java.awt.*;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.time.Instant;

/**
 * Handles GitHub Device Flow OAuth and Copilot session token management.
 *
 * Flow:
 *  1. getGitHubToken()       — device flow once, stored in ~/.github-editor-token
 *  2. getCopilotSessionToken() — short-lived token from copilot_internal API, auto-refreshed
 *
 * Attention: The usage of the copilot API was auto-generated by Claude Claude from reverse engineering
 * a Visual Code plugin. The support state of the API by GitHub is unknown and the integration may
 * break at any time. Use with caution.
 */
public class CopilotAuth {

    // Public client-id of the VS Code Copilot extension (well-known, used by many OSS clients)
    private static final String CLIENT_ID = "Iv1.b507a08c87ecfe98";
    private static final String DEVICE_CODE_URL = "https://github.com/login/device/code";
    private static final String ACCESS_TOKEN_URL = "https://github.com/login/oauth/access_token";
    private static final String COPILOT_TOKEN_URL = "https://api.github.com/copilot_internal/v2/token";
    private static final Path TOKEN_FILE = Path.of(System.getProperty("user.home"), ".github-editor-token");

    private final HttpClient http;
    private String cachedSessionToken;
    private Instant sessionTokenExpiry = Instant.EPOCH;

    public CopilotAuth() {
        this.http = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(10))
                .build();
    }

    /** Returns a valid Copilot session token, refreshing if necessary. */
    public synchronized String getCopilotSessionToken() throws Exception {
        if (cachedSessionToken == null || Instant.now().isAfter(sessionTokenExpiry.minusSeconds(60))) {
            refreshSessionToken();
        }
        return cachedSessionToken;
    }

    private void refreshSessionToken() throws Exception {
        String githubToken = getGitHubToken();
        HttpRequest req = HttpRequest.newBuilder()
                .uri(URI.create(COPILOT_TOKEN_URL))
                .header("Authorization", "token " + githubToken)
                .header("Accept", "application/json")
                .header("User-Agent", "GithubCopilot/1.155.0")
                .GET()
                .timeout(Duration.ofSeconds(10))
                .build();

        HttpResponse<String> resp = http.send(req, HttpResponse.BodyHandlers.ofString());
        if (resp.statusCode() != 200) {
            // GitHub token may be expired — delete and retry once
            Files.deleteIfExists(TOKEN_FILE);
            githubToken = getGitHubToken();
            req = HttpRequest.newBuilder()
                    .uri(URI.create(COPILOT_TOKEN_URL))
                    .header("Authorization", "token " + githubToken)
                    .header("Accept", "application/json")
                    .header("User-Agent", "GithubCopilot/1.155.0")
                    .GET()
                    .timeout(Duration.ofSeconds(10))
                    .build();
            resp = http.send(req, HttpResponse.BodyHandlers.ofString());
            if (resp.statusCode() != 200)
                throw new RuntimeException("Failed to get Copilot token: " + resp.body());
        }

        cachedSessionToken = extractJsonString(resp.body(), "token");
        long expiresAt = extractJsonLong(resp.body(), "expires_at");
        sessionTokenExpiry = Instant.ofEpochSecond(expiresAt);
    }

    /** Returns the stored GitHub OAuth token, triggering device flow if not present. */
    private String getGitHubToken() throws Exception {
        if (Files.exists(TOKEN_FILE)) {
            return Files.readString(TOKEN_FILE).strip();
        }
        String token = runDeviceFlow();
        Files.writeString(TOKEN_FILE, token);
        return token;
    }

    private String runDeviceFlow() throws Exception {
        // 1. Request device + user code
        HttpRequest req = HttpRequest.newBuilder()
                .uri(URI.create(DEVICE_CODE_URL))
                .header("Accept", "application/json")
                .header("Content-Type", "application/x-www-form-urlencoded")
                .POST(HttpRequest.BodyPublishers.ofString(
                        "client_id=" + CLIENT_ID + "&scope=read%3Auser"))
                .timeout(Duration.ofSeconds(10))
                .build();

        HttpResponse<String> resp = http.send(req, HttpResponse.BodyHandlers.ofString());
        String deviceCode = extractJsonString(resp.body(), "device_code");
        String userCode   = extractJsonString(resp.body(), "user_code");
        int interval      = (int) extractJsonLong(resp.body(), "interval");

        // 2. Show dialog to user
        showDeviceFlowDialog(userCode);

        // 3. Poll for token
        Instant deadline = Instant.now().plusSeconds(300);
        while (Instant.now().isBefore(deadline)) {
            Thread.sleep(interval * 1000L);
            HttpRequest pollReq = HttpRequest.newBuilder()
                    .uri(URI.create(ACCESS_TOKEN_URL))
                    .header("Accept", "application/json")
                    .header("Content-Type", "application/x-www-form-urlencoded")
                    .POST(HttpRequest.BodyPublishers.ofString(
                            "client_id=" + CLIENT_ID +
                            "&device_code=" + deviceCode +
                            "&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code"))
                    .timeout(Duration.ofSeconds(10))
                    .build();

            HttpResponse<String> pollResp = http.send(pollReq, HttpResponse.BodyHandlers.ofString());
            String body = pollResp.body();
            if (body.contains("access_token")) {
                return extractJsonString(body, "access_token");
            }
            // "authorization_pending" → keep polling; other errors → abort
            if (!body.contains("authorization_pending") && !body.contains("slow_down")) {
                throw new RuntimeException("Device flow failed: " + body);
            }
        }
        throw new RuntimeException("Device flow timed out");
    }

    private void showDeviceFlowDialog(String userCode) {
        SwingUtilities.invokeLater(() -> {
            JDialog dialog = new JDialog((Frame) null, "GitHub Copilot Authentifizierung", false);
            dialog.setLayout(new BorderLayout(10, 10));

            JPanel panel = new JPanel(new GridLayout(4, 1, 5, 5));
            panel.setBorder(BorderFactory.createEmptyBorder(15, 15, 10, 15));
            panel.add(new JLabel("Öffne im Browser:  https://github.com/login/device"));
            JTextField codeField = new JTextField(userCode);
            codeField.setFont(new Font(Font.MONOSPACED, Font.BOLD, 18));
            codeField.setEditable(false);
            codeField.setHorizontalAlignment(JTextField.CENTER);
            panel.add(codeField);
            panel.add(new JLabel("Gib den Code dort ein und autorisiere die App."));
            panel.add(new JLabel("Dieses Fenster schließt sich automatisch nach der Anmeldung."));
            dialog.add(panel, BorderLayout.CENTER);

            JButton closeBtn = new JButton("Schließen");
            closeBtn.addActionListener(e -> dialog.dispose());
            dialog.add(closeBtn, BorderLayout.SOUTH);

            dialog.pack();
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        });
    }

    // --- minimal JSON helpers (no external dependency) ---

    private String extractJsonString(String json, String key) {
        String search = "\"" + key + "\":\"";
        int idx = json.indexOf(search);
        if (idx == -1) return "";
        int start = idx + search.length();
        int end = start;
        while (end < json.length()) {
            char c = json.charAt(end);
            if (c == '\\') { end += 2; continue; }
            if (c == '"') break;
            end++;
        }
        return json.substring(start, end);
    }

    private long extractJsonLong(String json, String key) {
        String search = "\"" + key + "\":";
        int idx = json.indexOf(search);
        if (idx == -1) return 0;
        int start = idx + search.length();
        int end = start;
        while (end < json.length() && (Character.isDigit(json.charAt(end)) || json.charAt(end) == '-')) end++;
        try { return Long.parseLong(json.substring(start, end)); } catch (NumberFormatException e) { return 0; }
    }
}
