package specman.suggest.github;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

/**
 * Calls the internal GitHub Copilot completions endpoint.
 * Uses FIM (Fill-in-the-Middle): prompt = text before cursor, suffix = text after cursor.
 *
 * Attention: The usage of the copilot API was auto-generated by Claude Claude from reverse engineering
 * a Visual Code plugin. The support state of the API by GitHub is unknown and the integration may
 * break at any time. Use with caution.
 */
public class CopilotClient {

    private static final String COMPLETIONS_URL =
            "https://copilot-proxy.githubusercontent.com/v1/engines/copilot-codex/completions";

    private final HttpClient http;
    private final CopilotAuth auth;

    public CopilotClient() {
        this.auth = new CopilotAuth();
        this.http = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(10))
                .build();
    }

    public String complete(String contextBefore, String contextAfter) throws Exception {
        String sessionToken = auth.getCopilotSessionToken();

        String body = """
                {
                  "prompt": "%s",
                  "suffix": "%s",
                  "max_tokens": 100,
                  "temperature": 0,
                  "top_p": 1,
                  "n": 1,
                  "stream": true
                }
                """.formatted(escapeJson(contextBefore), escapeJson(contextAfter));

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(COMPLETIONS_URL))
                .header("Content-Type", "application/json")
                .header("Authorization", "Bearer " + sessionToken)
                .header("Editor-Version", "vscode/1.85.0")
                .header("Editor-Plugin-Version", "github/1.155.0")
                .header("Openai-Intent", "github-ghost")
                .header("User-Agent", "GithubCopilot/1.155.0")
                .POST(HttpRequest.BodyPublishers.ofString(body))
                .timeout(Duration.ofSeconds(15))
                .build();

        HttpResponse<String> response = http.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("Copilot API error " + response.statusCode() + ": " + response.body());
        }

        return extractStreamedText(response.body());
    }

    // Accumulates text from SSE stream: lines like "data: {...}"
    private String extractStreamedText(String body) {
        StringBuilder result = new StringBuilder();
        for (String line : body.split("\n")) {
            line = line.strip();
            if (!line.startsWith("data:")) continue;
            String json = line.substring(5).strip();
            if (json.equals("[DONE]")) break;
            int textIdx = json.indexOf("\"text\":\"");
            if (textIdx == -1) continue;
            int start = textIdx + 8;
            int end = start;
            while (end < json.length()) {
                char c = json.charAt(end);
                if (c == '\\') { end += 2; continue; }
                if (c == '"') break;
                end++;
            }
            String chunk = json.substring(start, end)
                    .replace("\\n", "\n").replace("\\r", "\r")
                    .replace("\\t", "\t").replace("\\\"", "\"").replace("\\\\", "\\");
            result.append(chunk);
        }
        return result.toString();
    }

    private String escapeJson(String text) {
        return text
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }


}
